# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEnxX_lSn-m2rqkCQXmb4A0rq47JEKRa
"""

!pip install gurobipy pandas matplotlib

import pandas as pd
import gurobipy as gp
from gurobipy import GRB

# 1.Lectura de archivos
df_bodegas = pd.read_csv('bodegas_candidatas.csv', index_col='id_bodega')
df_comunas = pd.read_csv('comunas_demandantes.csv', index_col='id_comuna')
df_transporte = pd.read_csv('matriz_transporte.csv')
df_demanda = pd.read_csv('demanda_proyectada.csv')

idx_min_tiempo = df_transporte.groupby(['id_bodega', 'id_comuna', 'vehiculo'])['tiempo_min'].idxmin()
df_transporte = df_transporte.loc[idx_min_tiempo].copy()


# 2. Definicion de variables
I = df_bodegas.index.tolist()
J = df_comunas.index.tolist()
K = df_demanda['insumo'].unique().tolist()
K_v = ['Agua_5L', 'Racion_24h_Familiar', 'Kit_Medico_Trauma', 'Medicamentos_Cronicos', 'Suplementos_Pediatricos']
K_n = ['Kit_Higiene_Familiar', 'Frazadas_Termicas', 'Carpas_Refugio', 'Herramientas_Remocion', 'Mascarillas_N95', 'Generador_Portatil', 'Baterias_D']
T = df_demanda['mes'].unique().tolist()
P = df_demanda['prioridad'].unique().tolist()
M = df_transporte['vehiculo'].unique().tolist()
C = df_bodegas['capacidad_m3'].to_dict()
F = df_bodegas['costo_fijo_CLP'].to_dict()
L_min = df_bodegas['personal_min'].to_dict()
E_max = df_bodegas['personal_max'].to_dict()


# 3. Definicion de parametros
demanda = df_demanda.set_index(['id_comuna', 'insumo', 'mes', 'prioridad'])['cantidad_unidades'].to_dict()

datos_transporte = df_transporte.set_index(['id_bodega', 'id_comuna', 'ruta', 'vehiculo'])

T_ijrm = datos_transporte['tiempo_min'].to_dict()

G_ijrm = datos_transporte['costo_viaje_CLP'].to_dict()

Apt_mjr = datos_transporte['aptitud'].to_dict()

volumen_k = {'Agua_5L': 0.005, 'Racion_24h_Familiar': 0.015, 'Kit_Medico_Trauma': 0.010, 'Medicamentos_Cronicos': 0.002, 'Suplementos_Pediatricos': 0.003, 'Kit_Higiene_Familiar': 0.012, 'Frazadas_Termicas': 0.020, 'Carpas_Refugio': 0.080, 'Herramientas_Remocion': 0.050, 'Mascarillas_N95': 0.005, 'Generador_Portatil': 0.150, 'Baterias_D': 0.001}

capacidad_m = {'Camioneta_4x4': 2.5, 'Camion_3_4': 18.0, 'Camion_Pesado': 45.0, 'Helicoptero': 4.0}

flota_Q = {'Camioneta_4x4': 30, 'Camion_3_4': 15, 'Camion_Pesado': 8, 'Helicoptero': 3}

tiempo_carga_desc = {'Agua_5L': 0.05, 'Racion_24h_Familiar': 0.08, 'Kit_Medico_Trauma': 0.1,'Medicamentos_Cronicos': 0.05, 'Suplementos_Pediatricos': 0.05, 'Kit_Higiene_Familiar': 0.08,'Frazadas_Termicas': 0.1, 'Carpas_Refugio': 0.25, 'Herramientas_Remocion': 0.15,'Mascarillas_N95': 0.05, 'Generador_Portatil': 0.5, 'Baterias_D': 0.05}

tiempo_operativo = {'Camioneta_4x4': 5.0, 'Camion_3_4': 10.0, 'Camion_Pesado': 20.0, 'Helicoptero': 15.0}

costos_insumos = {'Agua_5L': {'compra': 1500, 'bodegaje': 75}, 'Racion_24h_Familiar': {'compra': 12000, 'bodegaje': 600},'Kit_Medico_Trauma': {'compra': 45000, 'bodegaje': 2250},'Medicamentos_Cronicos': {'compra': 25000, 'bodegaje': 1250},'Suplementos_Pediatricos': {'compra': 18000, 'bodegaje': 900},'Kit_Higiene_Familiar': {'compra': 22000, 'bodegaje': 1100},
'Frazadas_Termicas': {'compra': 8500, 'bodegaje': 425}, 'Carpas_Refugio': {'compra': 85000, 'bodegaje': 4250},'Herramientas_Remocion': {'compra': 35000, 'bodegaje': 1750},'Mascarillas_N95': {'compra': 8000, 'bodegaje': 400},'Generador_Portatil': {'compra': 350000, 'bodegaje': 17500},'Baterias_D': {'compra': 4500, 'bodegaje': 225}}

tiempo_max_p = {1: 45, 2: 120, 3: 240}
eficiencia_rho = 0.75
horas_mes_d = 360
sueldo_mensual = 850000
ponderador_W = {1: 100, 2: 10, 3: 1}
penalidad_pi = {1: 20000, 2: 5000, 3: 1000}
factor_h = 0.0001
presupuesto_B = 5_000_000_000

parametros_wls = {"WLSACCESSID": "d1d2087a-5595-4edc-8c56-86b291b3d5b3","WLSSECRET": "087e5baa-b338-47f3-81ed-539ca3f6da57","LICENSEID": 2827565}
env = gp.Env(empty=True)
env.setParam('WLSACCESSID', parametros_wls["WLSACCESSID"])
env.setParam('WLSSECRET', parametros_wls["WLSSECRET"])
env.setParam('LICENSEID', parametros_wls["LICENSEID"])
env.start()

# 4. Generacion de conjunto de las rutas factibles

m = gp.Model("SENAPRED_Optimizacion_V3", env=env)
# Para n_ijrmtp
variable_n = []
# Para x_ijrkmtp
variable_x = []

for (i, j, r, m_veh) in datos_transporte.index:
    # Aplicamos R8 y solo consideramos combinaciones donde el vehículo es apto (Apt_mjr == 1)
    if Apt_mjr[i, j, r, m_veh] == 1:
        for t in T:
            for p in P:
                tiempo_total = T_ijrm[i, j, r, m_veh] + tiempo_operativo[m_veh]

                if tiempo_total <= tiempo_max_p[p]:
                    variable_n.append((i, j, r, m_veh, t, p))

                    for k in K:
                        variable_x.append((i, j, r, m_veh, t, p, k))

variable_n = gp.tuplelist(variable_n)
variable_x = gp.tuplelist(variable_x)

w = m.addVars(I, T, vtype=GRB.BINARY, name="w")
y = m.addVars(I, T, vtype=GRB.CONTINUOUS, name="y")
s = m.addVars(I, K, T, vtype=GRB.CONTINUOUS, name="s")
c = m.addVars(I, K, T, vtype=GRB.CONTINUOUS, name="c")
n = m.addVars(variable_n, vtype=GRB.INTEGER, name="n")
x = m.addVars(variable_x, vtype=GRB.CONTINUOUS, name="x")
e = m.addVars(I, T, vtype=GRB.CONTINUOUS, name="e")
f = m.addVars(J, K, T, P, vtype=GRB.CONTINUOUS, name="f")

m.update()

# 5. Definicion de funcion objetivo
tiempo_respuesta = gp.quicksum(ponderador_W[p] * (T_ijrm[i,j,r,m_veh] + tiempo_operativo[m_veh] + (2 * tiempo_carga_desc[k])) * x[i,j,r,m_veh,t,p,k]for (i,j,r,m_veh,t,p,k) in variable_x)

costo_operativo = factor_h * gp.quicksum(G_ijrm[i,j,r,m_veh] * n[i,j,r,m_veh,t,p]for (i,j,r,m_veh,t,p) in variable_n)

penalizacion_faltante = gp.quicksum(penalidad_pi[p] * f[j,k,t,p]for j in J for k in K for t in T for p in P)

m.setObjective(tiempo_respuesta + costo_operativo + penalizacion_faltante, GRB.MINIMIZE)

# 6. Definicion de restricciones

# R1. Satisfacción de demanda con holgura
m.addConstrs((x.sum('*', j, '*', '*', t, p, k) + f[j,k,t,p] >= demanda.get((j, k, t, p), 0) for j in J for k in K for t in T for p in P),name="R1_Demanda")

# R2. Balance de inventario general
for i in I:
    for k in K:
        for t in T:
            stock_anterior = 0 if t == 1 else s[i,k,t-1]
            m.addConstr(s[i,k,t] == stock_anterior + c[i,k,t] - x.sum(i, '*', '*', '*', t, '*', k),name=f"R2_Balance_{i}_{k}_{t}")

# R3. No acumulación de insmumos perecibles
m.addConstrs((s[i,k,t] == 0 for i in I for k in K_v for t in T),name="R3_Perecibles")

# R4. Capacidad física de bodega
m.addConstrs((gp.quicksum(volumen_k[k] * s[i,k,t] for k in K) <= C[i] * y[i,t] for i in I for t in T),name="R4_Capacidad_Fisica")

# R5. Capacidad de transporte en rutas del conjunto R'_{ijm}
m.addConstrs((gp.quicksum(volumen_k[k] * x[i,j,r,m_veh,t,p,k] for k in K if (i,j,r,m_veh,t,p,k) in variable_x)<= capacidad_m[m_veh] * n[i,j,r,m_veh,t,p] for (i,j,r,m_veh,t,p) in variable_n),name="R5_Capacidad_Transporte")

# R6a. Viajes condicionados a apertura de bodega
m.addConstrs((n[i,j,r,m_veh,t,p] <= flota_Q[m_veh] * y[i,t] for (i,j,r,m_veh,t,p) in variable_n),name="R6a_Viajes_Condicionados")

# R6b. Flujo físico de Kits condicionado a apertura
m.addConstrs((x[i,j,r,m_veh,t,p,k] <= demanda.get((j, k, t, p), 0) * y[i,t] for (i,j,r,m_veh,t,p,k) in variable_x),name="R6b_Flujo_Condicionado")

# R7. Disponibilidad de flota
m.addConstrs((n.sum('*', '*', '*', m_veh, t, '*') <= flota_Q[m_veh] for m_veh in M for t in T),name="R7_Flota_Regional")

# R8. Aptitud vehicular por ruta ya está garantizada porque no creamos las variables n donde Apt == 0 en la Fase 1.

# R9. Capacidad operativa y tiempo de cuadrillas
m.addConstrs((gp.quicksum((2 * tiempo_carga_desc[k]) * x[i_,j,r,m_veh,t_,p,k] for (i_,j,r,m_veh,t_,p,k) in variable_x.select(i, '*', '*', '*', t, '*', '*')) <= e[i,t] * 60 * horas_mes_d * eficiencia_rho for i in I for t in T),name="R9_Capacidad_Cuadrillas")

# R10a. Dotación mínima de personal
m.addConstrs((L_min[i] * y[i,t] <= e[i,t] for i in I for t in T),name="R10a_Personal_Min")

# R10b. Dotación máxima de personal
m.addConstrs((e[i,t] <= E_max[i] * y[i,t] for i in I for t in T),name="R10b_Personal_Max")

# R11. Capacidad de salida desde bodegas
for i in I:
    for k in K:
        for t in T:
            stock_anterior = 0 if t == 1 else s[i,k,t-1]
            m.addConstr(x.sum(i, '*', '*', '*', t, '*', k) <= stock_anterior + c[i,k,t],name=f"R11_Salida_Multiruta_{i}_{k}_{t}")

# R12a. Lógica de apertura única estratégica
m.addConstrs((gp.quicksum(w[i,t] for t in T) <= 1 for i in I),name="R12a_Apertura_Unica")

# R12b. Estado de operación continuo heredado
m.addConstrs((y[i,t] == gp.quicksum(w[i,tau] for tau in range(1, t+1)) for i in I for t in T),name="R12b_Operacion_Continua")

# R13. Presupuesto total regional
m.addConstr(gp.quicksum(F[i] * w[i,t] for i in I for t in T) +gp.quicksum(costos_insumos[k]['compra'] * c[i,k,t] for i in I for k in K for t in T) +gp.quicksum(costos_insumos[k]['bodegaje'] * s[i,k,t] for i in I for k in K for t in T) +
gp.quicksum(sueldo_mensual * e[i,t] for i in I for t in T) +gp.quicksum(G_ijrm[i,j,r,m_veh] * n[i,j,r,m_veh,t,p] for (i,j,r,m_veh,t,p) in variable_n)<= presupuesto_B,name="R13_Presupuesto_Total")


m.update()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 7. Configuramos el solver y iniciamos el programa

m.setParam('TimeLimit', 1800)
m.setParam('MIPFocus', 0)
m.setParam('Presolve', 1)
m.setParam('Heuristics', 0.05)
m.setParam('Cuts', 0)

m.optimize()


# 8. Estadisticas base del modelo

if (m.status == GRB.OPTIMAL) or (m.status == GRB.TIME_LIMIT and m.SolCount > 0):
    print(f"Cantidad total de variables      : {m.NumVars:,.0f}")
    print(f"Tiempo de resolución             : {m.Runtime:.2f} segundos")
    print(f"GAP de optimidad                 : {m.MIPGap * 100:.4f}%")
    print(f"Valor Función Objetivo (Z)       : {m.objVal:,.2f} minutos-eq.")

    # A. Reporte de Bodegas Abiertas
    df_bodegas = pd.DataFrame([
        {'Bodega': i, 'Mes_Apertura': t, 'Costo_Fijo_CLP': F[i], 'Dotacion': round(e[i,t].X, 0)}
        for i in I for t in T if w[i,t].X > 0.5])
    if not df_bodegas.empty: df_bodegas.to_csv("01_Reporte_Bodegas_Abiertas.csv", index=False)

    # B. Reporte de Faltante
    df_faltante = pd.DataFrame([
        {'Comuna': j, 'Insumo': k, 'Mes': t, 'Prioridad': p, 'Faltante': round(f[j,k,t,p].X, 1)}
        for j in J for k in K for t in T for p in P if f[j,k,t,p].X > 0.1])
    if not df_faltante.empty: df_faltante.to_csv("02_Reporte_insumo_Faltante.csv", index=False)

    # C. Reporte de Inventario
    df_inventario = pd.DataFrame([
        {'Bodega': i, 'Insumo': k, 'Mes': t, 'Stock_Final': round(s[i,k,t].X, 1)}
        for i in I for k in K for t in T if s[i,k,t].X > 0.1])
    if not df_inventario.empty: df_inventario.to_csv("03_Reporte_Inventario_Stock.csv", index=False)

    # 10. Extraccion datos analisis

    # 1. Desglose Presupuestario
    g_ape = sum(F[i] * w[i,t].X for i in I for t in T)
    g_com = sum(costos_insumos[k]['compra'] * c[i,k,t].X for i in I for k in K for t in T)
    g_bod = sum(costos_insumos[k]['bodegaje'] * s[i,k,t].X for i in I for k in K for t in T)
    g_per = sum(sueldo_mensual * e[i,t].X for i in I for t in T)
    g_tra = sum(G_ijrm[i,j,r,m_veh] * n[i,j,r,m_veh,t,p].X for (i,j,r,m_veh,t,p) in variable_n)
    pto_usado = g_ape + g_com + g_bod + g_per + g_tra

    df_finanzas = pd.DataFrame({'Categoria': ['Apertura', 'Compras', 'Bodegaje', 'Sueldos', 'Transporte'], 'Gasto_CLP': [g_ape, g_com, g_bod, g_per, g_tra]})
    df_finanzas.to_csv("04_Reporte_presupuestos.csv", index=False)

    # 2.Saturación de Personal
    datos_personal = []
    for i in I:
        for t in T:
            dotacion = e[i,t].X
            if dotacion > 0.5:
                minutos_usados = sum((2 * tiempo_carga_desc[k]) * x[i_,j_,r_,m_veh_,t_,p_,k_].X for i_, j_, r_, m_veh_, t_, p_, k_ in variable_x if i_ == i and t_ == t and x[i_,j_,r_,m_veh_,t_,p_,k_].X > 0.5)
                minutos_max = dotacion * 60 * horas_mes_d * eficiencia_rho
                sat = (minutos_usados / minutos_max) * 100 if minutos_max > 0 else 0
                datos_personal.append({'Bodega': i, 'Mes': t, 'Saturacion_%': round(sat, 1)})
    df_personal = pd.DataFrame(datos_personal)
    if not df_personal.empty: df_personal.to_csv("05_Reporte_Personal.csv", index=False)

    # 3.Tasa de Llenado de Vehículos
    datos_rutas = []
    for (i,j,r,m_veh,t,p) in variable_n:
        viajes = n[i,j,r,m_veh,t,p].X
        if viajes > 0.5:
            volumen_despachado = sum(volumen_k[k_val] * x[i_val,j_val,r_val,m_veh_val,t_val,p_val,k_val].X for i_val, j_val, r_val, m_veh_val, t_val, p_val, k_val in variable_x if i_val == i and j_val == j and r_val == r and m_veh_val == m_veh and t_val == t and p_val == p)
            capacidad_total_ruta = capacidad_m[m_veh] * viajes
            fill_rate = (volumen_despachado / capacidad_total_ruta) * 100 if capacidad_total_ruta > 0 else 0
            datos_rutas.append({'Origen': i, 'Destino': j, 'Vehiculo': m_veh, 'Mes': t, 'Viajes': int(viajes),'Volumen_Enviado_m3': round(volumen_despachado, 2), 'Fill_Rate_%': round(fill_rate, 1)})
    df_rutas = pd.DataFrame(datos_rutas)
    if not df_rutas.empty: df_rutas.to_csv("06_Reporte_Rutas.csv", index=False)


    # 9.Generacion de graficos
    plt.style.use('seaborn-v0_8-darkgrid')
    colores = ['#264653', '#2a9d8f', '#e9c46a', '#f4a261', '#e76f51']

    # 1. Gráfico de insumos
    if not df_faltante.empty:
        plt.figure(figsize=(6, 5))
        falt = df_faltante.groupby('Prioridad')['Faltante'].sum()
        falt.plot(kind='pie', autopct='%1.1f%%', colors=['#e63946', '#f4a261', '#e9c46a'][:len(falt)], startangle=90)
        plt.title('Grafico de insumos', fontweight='bold')
        plt.ylabel('')
        plt.tight_layout(); plt.savefig('G1_insumos.png', dpi=300)

    # 2. Uso de vehiculos
    if not df_rutas.empty:
        plt.figure(figsize=(8, 5))
        df_rutas.boxplot(column='Fill_Rate_%', by='Vehiculo', grid=True, patch_artist=True)
        plt.title('Tasa de uso de vehiculo', fontweight='bold')
        plt.suptitle('')
        plt.ylabel('% de Capacidad Utilizada por Viaje')
        plt.xlabel('Tipo de Vehículo')
        plt.xticks(rotation=15)
        plt.axhline(y=80, color='g', linestyle='--', alpha=0.5, label='Óptimo (>80%)')
        plt.legend()
        plt.tight_layout(); plt.savefig('G2_vehiculos.png', dpi=300)

    # 3. Gráfico de presupuesto
    plt.figure(figsize=(7, 5))
    plt.pie(df_finanzas['Gasto_CLP'], labels=df_finanzas['Categoria'], autopct='%1.1f%%', colors=colores)
    plt.title(f'Distribución de Recursos \n(Total Invertido: ${pto_usado/1e6:,.0f} Millones CLP)', fontweight='bold')
    plt.tight_layout(); plt.savefig('G3_presupuesto.png', dpi=300)

    # 4. Inventario vs demanda insatisfecha
    if not df_inventario.empty and not df_faltante.empty:
        plt.figure(figsize=(9, 5))
        inv_mes = df_inventario.groupby('Mes')['Stock_Final'].sum().reindex(range(1,13), fill_value=0)
        falt_mes = df_faltante.groupby('Mes')['Faltante'].sum().reindex(range(1,13), fill_value=0)

        ax1 = inv_mes.plot(kind='bar', color='#2a9d8f', alpha=0.7, label='Stock')
        ax2 = ax1.twinx()
        falt_mes.plot(kind='line', color='#e63946', marker='X', linewidth=2, ax=ax2, label='Demanda Insatisfecha')

        ax1.set_ylabel('Unidades en Stock')
        ax2.set_ylabel('Unidades Faltantes', color='#e63946')
        plt.title('Stock vs demanda', fontweight='bold')
        ax1.legend(loc='upper left'); ax2.legend(loc='upper right')
        plt.tight_layout(); plt.savefig('G4_stock.png', dpi=300)

elif m.status == GRB.INFEASIBLE:
    print("Modelo INFACTIBLE")